In [1]:
import pandas as pd
import numpy as np
import matplotlib as mlt
import matplotlib.pyplot as plt
import seaborn as sns
import scipy 


In [5]:
train = pd.read_csv('trainset.csv')
train=train.drop('Unnamed: 0',axis=1)

In [6]:
train.head()

Married Dependents  Education  ApplicantIncome  CoapplicantIncome  \
0        0          0          1         8.674197           0.000000   
1        1          1          1         8.430327           7.319202   
2        1          0          1         8.006701           0.000000   
3        1          0          0         7.857094           7.765993   
4        0          0          1         8.699681           0.000000   

   LoanAmount  Loan_Amount_Term  Credit_History Property_Area  Loan_Status  
0    1.790164                30             1.0   Rural/Urban            1  
1    1.768118                30             1.0   Rural/Urban            0  
2    1.649561                30             1.0   Rural/Urban            1  
3    1.757132                30             1.0   Rural/Urban            1  
4    1.784370                30             1.0   Rural/Urban            1

In [29]:
features = train.drop('Loan_Status',axis=1)
features=pd.get_dummies(features,drop_first=True)
target = train['Loan_Status']

In [36]:
features

Married  Education  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0          0          1         8.674197           0.000000    1.790164   
1          1          1         8.430327           7.319202    1.768118   
2          1          1         8.006701           0.000000    1.649561   
3          1          0         7.857094           7.765993    1.757132   
4          0          1         8.699681           0.000000    1.784370   
..       ...        ...              ...                ...         ...   
609        0          1         7.972811           0.000000    1.663294   
610        1          1         8.320448           0.000000    1.550446   
611        1          1         8.996280           5.484797    1.877529   
612        1          1         8.933796           0.000000    1.830410   
613        0          1         8.430327           0.000000    1.774586   

     Loan_Amount_Term  Credit_History  Dependents_1  Dependents_2  \
0                  30             1.0             0             0   
1                  30             1.0             1             0   
2                  30             1.0             0             0   
3                  30             1.0             0             0   
4                  30             1.0             0             0   
..                ...             ...           ...           ...   
609                30             1.0             0             0   
610                15             1.0             0             0   
611                30             1.0             1             0   
612                30             1.0             0             1   
613                30             0.0             0             0   

     Dependents_3+  Property_Area_Semiurban  
0                0                        0  
1                0                        0  
2                0                        0  
3                0                        0  
4                0                        0  
..             ...                      ...  
609              0                        0  
610              1                        0  
611              0                        0  
612              0                        0  
613              0                        1  

[614 rows x 11 columns]

# KNN

In [139]:
from sklearn.preprocessing import normalize
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
param = {'n_neighbors':np.arange(1,25,5),'weights':['uniform', 'distance'] }
knn = KNeighborsClassifier()
clf = GridSearchCV(knn, param)
clf.fit(features,traget)
knn = KNeighborsClassifier(n_neighbors=21, weights='distance')
knn.fit(features,traget)

KNeighborsClassifier(n_neighbors=21, weights='distance')

In [41]:
knn = KNeighborsClassifier(n_neighbors=21, weights='distance')
knn.fit(features,traget)

KNeighborsClassifier(n_neighbors=21, weights='distance')

In [126]:
y_pre=knn.predict(features)

In [140]:
cross_val_score(knn,features,target)

array([0.76422764, 0.70731707, 0.72357724, 0.75609756, 0.74590164])

# logistic Regression

In [93]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000,C=11)
lr.fit(features,target)
y_pre_lr=lr.predict(features)
y_pre_lr_proba=lr.predict_proba(features)

In [94]:
confusion_matrix(target,y_pre_lr)

array([[ 92, 100],
       [ 40, 382]], dtype=int64)

In [118]:
cross_val_score(lr,features,target)

array([0.79674797, 0.74796748, 0.72357724, 0.78861789, 0.77868852])

In [151]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
svcrbf = SVC(kernel = 'rbf',probability=True,C=100)
svcrbf.fit(features,target)
y_val_pred = svcrbf.predict(features)
confusion_matrix(target,y_val_pred)

array([[ 95,  97],
       [ 41, 381]], dtype=int64)

In [152]:
cross_val_score(svcrbf,features,target)

array([0.80487805, 0.7398374 , 0.73170732, 0.78861789, 0.80327869])